add keyboard
Domino5740/epic_racer pull request #2
Opened 2020-08-11 20:22 UTC by Wiktoria0723

2020-08-11 20:46 UTC, r4jmond requested changes
jak to w ogóle nic nie robi ten kod chyba, pozdrawiam

2020-08-11 20:46 UTC, Domino5740 commented on Keyboard.v
> +	end
nie może być initial

2020-08-11 20:46 UTC, Domino5740 commented on Keyboard.v
> +	end
czy ta częstotliwość będzie odpowiednia? czy to testowałaś i działa na symulacji chociaż?

2020-08-11 20:46 UTC, Domino5740 commented on Keyboard.v
> +   );
a gdzie tu w ogóle jakieś wyjście/wyjścia mówiące nam o tym chociażby jaki klawisz został naciśnięty?

2020-08-11 20:46 UTC, Domino5740 commented on Keyboard.v
> +	wire [7:0] ESC = 8'h76;
jak rozumiem to są stałe? jako localparam polecam zdefiniować, lub też dyrektywą define

2020-08-11 20:46 UTC, Domino5740 commented on Keyboard.v
> +*/
a to do wyrzucenia oczywiście

2020-08-11 20:50 UTC, Wiktoria0723 commented on Keyboard.v
> +*/
no przecież to jest w komentarzu

2020-08-11 20:51 UTC, Domino5740 commented on Keyboard.v
> +*/
a no jest owszem ale jest zbędne

2020-08-11 20:52 UTC, Wiktoria0723 commented on Keyboard.v
> +   );
to jest dobre pytanie

2020-08-11 20:53 UTC, Wiktoria0723 commented on Keyboard.v
> +	end
to się zmieni

2020-08-11 20:53 UTC, Wiktoria0723 commented on Keyboard.v
> +*/
to się ofc usunie 
zostawiłam na razie, jakby co

2020-08-13 22:45 UTC, r4jmond requested changes
no nareszcie wygląda na coś co ma ręce i nogi 😊

2020-08-13 22:45 UTC, Domino5740 commented on keyboard.v
> +		);
a tego modułu to tu nie widzę słuchaj

2020-08-13 22:45 UTC, Domino5740 commented on keyboard.v
> +    end
(┬┬﹏┬┬) zwracaj uwagę na wcięcia proszę, i nie tylko tu jest ten błąd (┬┬﹏┬┬)

2020-08-13 22:45 UTC, Domino5740 commented on keyboard.v
> +         key_nxt = ARROW_LEFT_state;
to ARROW_LEFT_STATE ITD, jak rozumiem to te "nawiązania do stanów"?
nazwij to sobie po prostu ARROW_LEFT_KEY i w localparamach zdefiniuj kodem graya(nie mylić z greya hehe)

2020-09-13 10:51 UTC, closed without merging